### ISSUE TITLE
Average Episode Last Distance

### ISSUE THREAD

**Issue by Captain6606** [wuxiyang1996/iPLAN#2]
Why isn't Average Episode Last Distance printed to my console：

Episode # 8  | Current time step:  784  | Average Episode Reward:  -163.39656672150198  | Average Episode Length:  49.0
Behavior Loss 0  | Stability Loss 0  | Behavior Total Loss 0
Prediction Loss 0

**Comment by wuxiyang1996** [comment]
Average Episode Last Distance is generally an expired metric in the code

**Comment by Captain6606** [comment]
ok
